### ISSUE TITLE
New versioned release?

### ISSUE THREAD

**Issue by thenonsequitur** [rafaelcaricio/thumbor_rails#9]
Would it be possible to release a new version of the gem containing the new changes since 1.1.0 (or are there already plans to do so at some point)?

We rely on the bugfix that was merged in here: https://github.com/rafaelcaricio/thumbor_rails/commit/2c20826d7d5377f223e646520fc7c0afb2a8e551. But that was merged in after the 1.1.0 release.

We could directly reference the repo+sha commit, but we'd like to use a standard versioned gem if we can.

**Comment by rafaelcaricio** [comment]
@thenonsequitur Thanks for reporting that. I will upload the new version.

**Comment by rafaelcaricio** [comment]
@thenonsequitur I just released the new version [1.2.0](https://rubygems.org/gems/thumbor_rails/versions/1.2.0). Let me know if you need anything more.

**Comment by thenonsequitur** [comment]
Thank you, much appreciated!
